### ISSUE TITLE
질문드립니다.

### ISSUE THREAD

**Issue by leejh7787** [huhji/licence_plate_recognition_korea#1]
Traceback (most recent call last):
  File "dr.py", line 237, in <module>
    label = labels[-1]
IndexError: list index out of range

이부분에서막히는데 도움좀주실수있나요

**Comment by jihyun-huh** [comment]
labels에는 API로 탐지한 text 중 번호판 형태를 가진 것만 담게 되는데
이 경우,
1. API가 작동하지 않았거나
2. 사진 안에 번호판이 없거나
3. API가 작동은 하되, 글자 인식을 못한 것 같습니다.

**Comment by leejh7787** [comment]
제가 수정한 부분이
path = "C:/Users/jhlee/anaconda3/envs/tf3/licence_plate_recognition_korea-master/Images/hhh.jpg"

  cv.imwrite("C:/Users/jhlee/Desktop/sdf.jpg", img)
인데
수정안하고 돌리면
 FileNotFoundError: [Errno 2] No such file or directory: '/Images/video_captioned.jpg' 이런에러가나오네요

실행은 python dr.py --image images/hhh.jpg로하였습니다.

1.혹시 api는 path/to/key.json 으로 지정하나요? 아니면 개인api를이용하나요?
2.path 부분에 어떤것의 경로를 집어넣어야 하나요?
3.model.weights는 어디서 구하나요?

답변해주시면 감사하겠습니다 
초보자라 많이 미숙하네요

**Comment by jihyun-huh** [comment]
1. api는 google과 naver측에 api 사용 신청 후 받는 개인 key를 사용하셔야합니다.
2. 'Images/video_captioned.jpg' 해당 코드를 path로 수정하셔야 합니다.
혹은, 함께 fork 하신 Images 내부 파일을 사용하시면 됩니다.
3. model.weights는 [link](https://drive.google.com/file/d/1vXjIoRWY0aIpYfhj3TnPUGdmJoHnWaOc/edit) 여기서 다운로드 받으실 수 있습니다.

**Comment by jihyun-huh** [comment]
그리고 저도 연구용이라 필요한 부분만 입맛대로 바꾸고 깔끔하게 코드를 짜진 못했었는데,
https://github.com/alitourani/yolo-license-plate-detection 이분 코드를 참고하시면 훨씬 도움이 되실겁니다.
저도 참고한 코드입니다!

**Comment by leejh7787** [comment]
감사합니다 추천해주신 코드로  같은 동영상을 돌리면 동작하는데

번호판글자 추출을 원해서 여기서 돌리면
Traceback (most recent call last):
File "dr.py", line 237, in
label = labels[-1]
IndexError: list index out of range 
에러가뜨는데 같은 동영상을 돌렸으므로
1.제가 api적용을 잘못한거같아서 뜨는거같아요!
저는google api적용법을 서칭하여 거기서하라는대로 키를만들고 다운받아
 setx GOOGLE_APPLICATION_CREDENTIALS C:/Users/jhlee/Desktop/ket.json을적용하였습니다.
api를 어떻게 적용해야 하는지 알려주실수있나요? 죄송합니다 
저는 동영상을 input으로 넣고있습니다.
염치없지만 부탁드려봅니다.

path에 넣는 jpg파일은 돌리고싶은  jpg파일의 경로를 넣는건가요? 
아니면 저의 api json파일 경로를 집어넣는건가요?

2.
traceback (most recent call last):
  File "licence_plate_detection.py", line 213, in <module>
    match_pattern = re.search(pattern2, recoq[0])
IndexError: list index out of range
초반인식을위해 pattern과pattren2를바꾸어보았는데 이런에러는 범위차이인가요?
